
- name: install ozone
  hosts: all
  become: true

  tasks:
  - name: Copy ozone-site.xml
    copy:
      src: ./ozone/config/ozone-site.xml
      dest: /hadoop/app/ozone/etc/hadoop/ozone-site.xml
      owner: ozone
      group: hadoop
      mode: '0644'


